### ISSUE TITLE
Crash on fake/nil players running actions

### ISSUE THREAD

**Issue by heavygale** [rubenwardy/awards#59]
Runtime error from mod 'awards' in callback node_on_dig(): [awards/api.lua:224](https://github.com/rubenwardy/awards/blob/master/api.lua#L222): assertion failed!
`assert(player and player.is_player and player:is_player() and key)`

caused by self-digging plants in plantlife_modpack e.g. [ferns/treefern.lua#L143](https://github.com/minetest-mods/plantlife_modpack/blob/master/ferns/treefern.lua#L143)
`minetest.dig_node({x=pos.x,y=pos.y+1,z=pos.z})`

Maybe there's no player set in this case?
As a workaround on my server I changed the `assert` to `if`.

----------
When looking into the code I additionally noticed that [line 242](https://github.com/rubenwardy/awards/blob/master/api.lua#L242) can't be reached because of the return in [line 239](https://github.com/rubenwardy/awards/blob/master/api.lua#L239).

**Comment by poikilos** [comment]
@rubenwardy here's a traceback: <https://pastebin.com/dDBg40vf>

**Comment by poikilos** [comment]
uhoh...it also happens when lava burns fern tree without user interaction: <https://pastebin.com/xfRJHfMS>

**Comment by FaceDeer** [comment]
Hi, I've had a player run into this problem with Digtron. Digtron also uses a fake player object when doing digging operations and the fake player's is_player returns false, since it's not actually a player doing the digging. I would think Awards should just discard non-player diggers rather than crashing on it, since it wouldn't make sense to grant awards to mechanisms or other autonomous scripts for doing stuff like this (Digtron has custom award granting code for players digging with it).
